import test from 'node:test';
import assert from 'node:assert/strict';
import {gameApi} from '../src/game-api.mjs';
const origin='https://game.invalid',env={GAME_SESSION_SECRET:'test-only-secret',GEMINI_API_KEY:'test-only-key'};
async function session(){const r=await gameApi(new Request(origin+'/api/hotel/status'),env);const d=await r.json();return {token:d.csrfToken,cookie:r.headers.get('set-cookie').split(';')[0],status:d};}
test('game status issues a signed HttpOnly session without revealing provider secrets',async()=>{const s=await session();assert.equal(s.status.configured,true);assert.equal(s.status.chapter,'hotel');assert.doesNotMatch(JSON.stringify(s),/test-only-secret|test-only-key/);});
test('cross-site, missing cookie and tampered sessions fail before upstream calls',async()=>{const s=await session();let calls=0;const send=headers=>gameApi(new Request(origin+'/api/hotel/interpret',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:'{}'}),env,()=>{calls++;});for(const headers of [{},{'X-Voice-Token':s.token},{'X-Voice-Token':s.token,Cookie:s.cookie,Origin:'https://other.invalid'},{'X-Voice-Token':s.token+'x',Cookie:s.cookie}])assert.equal((await send(headers)).status,403);assert.equal(calls,0);});
test('malformed inputs and unknown endpoints cannot make paid calls',async()=>{const s=await session();let calls=0;const fetchImpl=()=>{calls++;};const headers={'X-Voice-Token':s.token,Cookie:s.cookie,'Content-Type':'application/json'};assert.equal((await gameApi(new Request(origin+'/api/hotel/interpret',{method:'POST',headers,body:'not json'}),env,fetchImpl)).status,400);assert.equal(await gameApi(new Request(origin+'/api/other/interpret'),env,fetchImpl),null);assert.equal(calls,0);});
test('a stalled upload has an eight-second deadline and does not reserve provider capacity',async t=>{const s=await session();let cancelled=false;const stream=new ReadableStream({cancel(){cancelled=true;}});const pending=gameApi(new Request(origin+'/api/hotel/interpret',{method:'POST',duplex:'half',headers:{'X-Voice-Token':s.token,Cookie:s.cookie,'Content-Type':'application/json'},body:stream}),env,()=>{throw Error('must not fetch');});const r=await pending;assert.equal(r.status,408);assert.equal(cancelled,true);});
